project_id = "fqasdjuwskbhwmaswmnf"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://8a66be13-061d-42b5-8a77-85f1c1c4b93a.lovableproject.com"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_refresh_token_reuse_interval = 10
enable_signup = true

[functions.notify-doctor]
verify_jwt = false