// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fqasdjuwskbhwmaswmnf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZxYXNkanV3c2tiaHdtYXN3bW5mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NDU4NDEsImV4cCI6MjA3MzUyMTg0MX0.dkLc5I0COTFo0hw6eI5NnGnvLQC0OpW5YkIGgaCBgsE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});